alert("Olá, seja Bem vindo")
console.log("posso escrever aqui também")
console.log(10+2)
console.log(10-2)
console.log(10*2)
console.log(10/5)
alert("10" + 2)
console.log("João" + "" + " Paulo")
console.log(parseFloat("10")+2)